name: cbert
channels:
    - anaconda
    - pytorch
dependencies:
    - python==3.7.6
    - pytorch==1.4.0
    - numpy==1.18.1
    - scikit-learn==0.22
    - pandas==1.0.3
    - pip
    - pip:
        - transformers==2.3.0
        - tqdm==4.43
        - torch==1.4.0
